from apps.magic8ball import magic_8_ball
from apps.diceroller import dice_roller
from apps.bro import get_bro
from apps.rockpaperscissors import rock_paper_scissors
from apps.wiki import wiki_search
from apps.btc import btc_value
from apps.weather import get_weather
from apps.event import Event
from apps.trivia import trivia_question
from apps.pfspells import embed_spell
from apps.mtgsearch import fuzzy_search_card_name
